# Install Python and system libraries
[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "libgl1", "libglib2.0-0", "gcc", "g++", "make"]

[phases.install]
cmds = [
    "python3 -m venv --system-site-packages /opt/venv",
    "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "sh -c 'export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH && /opt/venv/bin/uvicorn api.api:app --host 0.0.0.0 --port $PORT'"

