# Let Nixpacks auto-detect Python from requirements.txt
# Only specify additional system libraries needed for OpenCV at runtime
[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0", "gcc", "g++", "make"]

