[phases.setup]
nixPkgs = ["python311", "libGL", "glib", "libxcrypt-legacy"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn api.api:app --host 0.0.0.0 --port $PORT"

