# Install Python and system libraries via apt
[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "libgl1", "libglib2.0-0", "gcc", "g++", "make"]

[phases.install]
cmds = [
    "pip3 install --no-cache-dir --break-system-packages -r requirements.txt"
]

[start]
cmd = "sh -c 'export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH && python3 -m uvicorn api.api:app --host 0.0.0.0 --port $PORT'"

